package com.example.trafficsignapp.data.route


import androidx.room.*
import com.example.trafficsignapp.data.detection.DetectedSignEntity


@Dao
interface RouteDao {

    /** 1️⃣ Create a new route and return its autogenerated ID */
    @Insert
    fun createRoute(route: Route): Long

    /** 2️⃣ Link a detection into a route */
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    fun linkDetection(ref: RouteDetectionCrossRef)

    /** 3️⃣ Update only the `endTime` of an existing route */
    @Query("UPDATE routes SET endTime = :endTime WHERE routeId = :routeId")
    fun updateEndTime(routeId: Long, endTime: Long): Int

    /** 4️⃣ Get a full route with its detections attached */
    @Transaction
    @Query("SELECT * FROM routes WHERE routeId = :id")
    fun getRouteWithDetections(id: Long): RouteWithDetections

    // ← Add this NEW method:
    @Query("SELECT * FROM routes WHERE routeKey = :routeKey LIMIT 1")
    fun findByKey(routeKey: String): Route?

    /** 5️⃣ (Optional) List all routes for a given user */
    @Query("SELECT * FROM routes WHERE userId = :userId ORDER BY startTime DESC")
    fun getAllRoutesForUser(userId: String): List<Route>
}
